
###
GET http://localhost:8080/api/products?category=guardapolvo&type=nivel_inicial
###
GET http://localhost:8080/api/products/guardapolvos/66c6248b94fcdcb275cfe304
###
GET http://localhost:5173/api/products?id=68387e212126558b5189665d

###
POST http://localhost:8080/api/products/clearCache


###
DELETE http://localhost:8080/api/products/guardapolvos/668af0509583f9a6591cab48
Authorization: Beared eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2Njg1ZTUzNmVjYTI0Y2Q0ZWIyM2ZlYmQiLCJpYXQiOjE3MjAzODExMjEsImV4cCI6MTcyMDQwOTkyMX0.YOyQkUq0_s-wdhOzcq9qL5j_E9Uk2dqcissIPcpH8Gw
###
POST http://localhost:8080/api/products/guardapolvos HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2Njg1ZTUzNmVjYTI0Y2Q0ZWIyM2ZlYmQiLCJpYXQiOjE3MjQxNzAwMjgsImV4cCI6MTcyNDE5ODgyOH0.GS-YGmqUbji3LdLN-diU2KJ1gcPSYbto3XC644lQGWc


{
    "name": "prueba9",
    "type": "Guardapolvo",
    "amount": 0,
    "amountToBuy": 5,
    "price": 32000,
    "discountPrice": 30000,
    "size": 0,
    "img": "nn",
    "img2": "nn",
    "table": "stock",
    "description": {
        "general": "El Carola es un diseño súper práctico por la posibilidad de guardado debido a la cantidad y amplitud de los bolsillos. Posee cierre     general: 'El Carola es un diseño súper práctico por la posibilidad de guardado debido a la cantidad y amplitud de los bolsillos. Posee cierre frontal y 2 cierres diente de perro plásticos en los bolsillos. La espalda es toda del mismo color. Haz zoom y enamórate de los detalles!!!",     
        "base": "Cuadrille intermedio Francia",
        "detalle": "Animal Print estampado",
        "vivos": "Negros",
        "bolsillos": "Animal Print + Gliter negro."
  }
}

###
PUT http://localhost:8080/api/products/guardapolvos/6685ef6fc71667eac4aea0c8 HTTP/1.1
content-type: application/json

{
    "type" : "guardapolvo"
}

###
POST http://localhost:8080/api/products/guardapolvos/updateField HTTP/1.1
content-type: application/json

###
POST http://localhost:8080/api/products/guardapolvos/deleteField HTTP/1.1
content-type: application/json

{
  "field": "listedPrice"
}

###
POST http://localhost:8080/api/products/guardapolvos/changePriceByPorcentage HTTP/1.1
content-type: application/json

# {
#   "porcent": 0.12,
#   "guardapolvos": []
# }