
GET http://localhost:8080/api/payments

###
POST http://localhost:8080/api/payments HTTP/1.1
content-type: application/json

###
PUT http://localhost:8080/api/payments/6685fad08053115930d87b29 HTTP/1.1
content-type: application/json

{
  "priceShipmentSucursal": "5000",
  "priceShipmentDomicilio": "8000",
  "bancoFrances": {
    "imgQr": "https://pacucostorage.blob.core.windows.net/guardapolvos-dev/1748616136456-431255556-qr-pago-banco-frances.png"
  },
  "mercadoPago": {
    "currentUser": "Prueba Juan Arca",
    "currentUserPublicKey": "ASDF_NSIDF23084093284293084092"
  },
  "transferencia": {
    "cbu": "1289409218309",
    "aliasCbu": "eppe-pep",
    "titularCuentaCbu": "juan carlos",
    "savedProfiles": {
      "Adry": {
          "cbu": "1289409218309",
          "aliasCbu": "eppe.pep",
          "titularCuentaCbu": "juan carlos" 
      },
      "Aldi": {
          "cbu": "123498371298",
          "aliasCbu": "lucas.poepoe",
          "titularCuentaCbu": "Aldana"
      }
    }
  }
}

###
PATCH http://localhost:8080/api/payments/clean/6685fad08053115930d87b29 HTTP/1.1
content-type: application/json