
GET http://localhost:8080/api/payments

###
POST http://localhost:8080/api/payments HTTP/1.1
content-type: application/json

###
PUT http://localhost:8080/api/payments/66758b2b64c03ef4951806be HTTP/1.1
content-type: application/json

{
  "priceShipmentSucursal": "6000",
  "priceShipmentDomicilio": "8000",
  "bancoFrances": {
    "imgQr": "https://pacucostorage.blob.core.windows.net/guardapolvos-dev/1748616136456-431255556-qr-pago-banco-frances.png"
  },
  "mercadoPago": {
    "currentUser": "",
    "currentUserPublicKey": ""
  },
  "transferencia": {
    "cbu": "0000003100026313332638",
    "aliasCbu": "aldiparo.mp",
    "titularCuentaCbu": "Aldana Belen Parodi",
    "savedProfiles": {
      "Adry": {
          "cbu": "0140024303502657621621",
          "aliasCbu": "pacuco.love",
          "titularCuentaCbu": "Adriana Francisco" 
      },
      "Aldi": {
          "cbu": "0000003100026313332638",
          "aliasCbu": "aldiparo.mp",
          "titularCuentaCbu": "Aldana Belen Parodi"
      }
    }
  }
}

###
PATCH http://localhost:8080/api/payments/clean/6685fad08053115930d87b29 HTTP/1.1
content-type: application/json