


GET http://localhost:8080/api/purchasedProduct
###
GET http://localhost:8080/api/purchasedProduct/68508b5d51ab69da1b34961f
###
GET http://localhost:8080/api/purchasedProduct/get/onlyTimes
###
GET http://localhost:8080/api/purchasedProduct/get/topPaymentMethods
###


DELETE http://localhost:8080/api/purchasedProduct/6683317de68ddb78136d7377
###
POST http://localhost:8080/api/purchasedProduct HTTP/1.1
content-type: application/json

{
    "operationCode": "1234567",
    "clientData": {"name":"franco"},
    "totalPricePurchased": "90",
    "time": "12:30"
}

###
PUT http://localhost:8080/api/purchasedProduct/683894192126558b5189668e HTTP/1.1
content-type: application/json

{
    "time": "11/6/2025, 11:50:38"
}

###
PUT http://localhost:8080/api/purchasedProduct/update/time HTTP/1.1
content-type: application/json